apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
spec:
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
