apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
