{{- if eq (include "discovery.isOpenShift" .) "true" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "discovery.fullname" . }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
spec:
  host: {{ .host }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ include "discovery.serverFullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end -}}
